name: wampproto
description: Sans-IO WAMP protocol implementation
version: 0.1.0
repository: https://github.com/xconnio/wampproto.dart

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  cbor: ^6.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
